---
- name: Create ec2 Instance
  hosts: localhost
  tasks:
  - name: Create ec2 Instance Play
    amazon.aws.ec2_instance:
      region: us-east-1 # US East, Ohio
      key_name: ec2-keypair # Key used to log in
      instance_type: t2.micro
      image_id: ami-08e637cea2f053dfa # RHEL9 AMI
      wait: yes
      state: running
      count: 1 # Create 1 EC2 Instance
      vpc_subnet_id: subnet-09d6f99a7a4fd5b9e
      tags:
        Environment: test
    register: ec2_result
    delegate_to: localhost
    
  # Play to display new instance_id of ec2 to screen
  - name: Display results
    debug:
      var: ec2_result.instance_ids

  - name: Add Elastic IP to instance
    amazon.aws.ec2_eip:
      region: us-east-1 # US East, Ohio
      device_id: "{{ ec2_result.instance_ids[0] }}"
      ip: 35.170.124.149

  - name: Install webserver
    dnf:
       name: httpd
       state: present
       
