---
- name: Create ec2 Instance
  hosts: localhost
  tasks:
  # Create a new ec2 instance 
  - name: Create ec2 Instance Play
    amazon.aws.ec2_instance:
      region: us-east-2 # US East, Ohio
      key_name: ec2_keypair # Key used to log in
      instance_type: t2.micro
      image_id: ami-092b43193629811af # RHEL8 AMI
      wait: yes
      count: 1 # Create 1 EC2 Instance
      vpc_subnet_id: subnet-00c58b63ae2bb7796
      tags:
        Environment: test
    register: ec2_result
    delegate_to: localhost
    
  # Play to display new instance_id of ec2 to screen
  - name: Display results
    debug:
      var: ec2_result.instance_ids
