---
- name: Create EC2 Instance
  hosts: localhost
  tasks:
  - name: Create EC2 Instance Play
    amazon.aws.ec2_instance:
      region: us-east-2 # US East, Ohio
      key_name: ec2_keypair # Key used to log in
      instance_type: t2.micro
      image_id: ami-092b43193629811af # RHEL8 AMI
      wait: yes
      count: 1 # Create 1 EC2 Instance
      vpc_subnet_id: subnet-00c58b63ae2bb7796
      tags:
        Environment: test
    delegate_to: localhost
